### ISSUE TITLE
Ошибка Error while executing account-script: extract() called on unit value 

### ISSUE THREAD

**Issue by IgorShadurin** [wavesplatform/private-node-docker-image#1]
Приветствую! Запускаю ноду по инструкции: https://habr.com/ru/company/waves/blog/459773/
Тестирую этот смарт-контракт: https://gist.github.com/IgorShadurin/e6aac15618128b21643117831b56a0d4
с помощью этого теста https://gist.github.com/IgorShadurin/850941c5accdf68885dba52dbef017f0

При запуска на приватной ноде с помощью команды "surfboard test" получаю ошибку: "Error: Error while executing account-script: extract() called on unit value"

При запуске теста на тестнете с помощью команды "surfboard test --env=testnet" ошибка не происходит.

В чем может быть проблема и как ее решить?

**Comment by msmolyakov** [comment]
Привет!
Нода, которая поднимается в этом docker контейнере, изолирована и работает сама с собой: она ничего не знает о тестнете или каких-то других сетях.
Твой контракт рассчитан только на работу в тестнете, т.к. в нем явно указан адрес из тестнета:
`let ServerAddress = addressFromStringValue("3MuJmCSEUgBNy1R2gesk59xDbWcuTKwwixW")`
Возможно, что-то еще.

Попробуй указать другой адрес (из кастомной сети) и проверь, что дальше по контракту не используется что-либо из тестнета.
